// Floodlit Clubhouse reminder: landing storytelling uses an off-axis network field and disciplined court-lime signals.
import { motion, useInView } from "framer-motion";
import { ArrowRight, CheckCircle2, ChevronRight, Compass, MapPin, Play, ShieldCheck, UsersRound } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { Link } from "wouter";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { BrandMark } from "@/components/Brand";
import { AthleteCard, PricingCard, SectionKicker } from "@/components/ProductPrimitives";
import { athletes, cities, subscriptionPlans } from "@/lib/mock-data";

function Counter({ value, suffix }: { value: number; suffix: string }) {
  const ref = useRef<HTMLSpanElement>(null);
  const visible = useInView(ref, { once: true, margin: "-80px" });
  const [count, setCount] = useState(0);
  useEffect(() => { if (!visible) return; let current = 0; const timer = window.setInterval(() => { current += Math.max(1, Math.ceil(value / 34)); if (current >= value) { setCount(value); window.clearInterval(timer); } else setCount(current); }, 28); return () => window.clearInterval(timer); }, [visible, value]);
  return <span ref={ref}>{count}{suffix}</span>;
}

const faqs = [
  ["What is ClubOfSports?", "ClubOfSports is a sports identity and local discovery space that helps athletes find compatible players, useful events and real sessions."],
  ["Which sports are supported?", "The demo includes badminton, cricket, football, running, chess and swimming, with the data structure ready for more sports."],
  ["Can I add multiple sports?", "Yes. Your primary sport shapes your first recommendations, while additional sport profiles make it easier to find the right kind of playing partner."],
  ["How does athlete matching work?", "Match explanations use sport compatibility, skill level, proximity and availability—so you can see why a recommendation is useful before you connect."],
  ["How does the trust score work?", "The score rewards a complete profile, verified sessions, completed matches and positive sports-community interactions. It is not a social popularity score."],
  ["Can I find athletes in another city?", "Multi-city discovery is available as a Club Pro feature. The free experience remains useful for the city you play in most."],
  ["Can I schedule recurring sports sessions?", "Yes. Club members can set a repeating weekly venue session; Club Pro can also plan weekends and monthly routines."],
  ["What does the premium plan provide?", "Paid plans add matching depth, recurring scheduling and, for Club Pro, an AI-assisted way to turn a natural-language request into a focused player search."],
];

export default function Landing() {
  return <div className="landing-page"><header className="landing-nav"><BrandMark /><nav><a href="#how-it-works">How it works</a><a href="#sports">Sports</a><a href="#faq">FAQ</a></nav><div><Link href="/onboarding" className="nav-login">Log in</Link><Link href="/onboarding" className="button-lime">Get started <ArrowRight size={16} /></Link></div></header>
    <main>
      <section className="hero-section"><div className="hero-glow" /><img className="hero-photo" src="/manus-storage/clubofsports-hero-network_51805421.jpg" alt="Athletes across different sports connected through ClubOfSports" /><div className="hero-overlay" /><div className="hero-copy"><motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.45 }}><SectionKicker>THE ATHLETE NETWORK</SectionKicker><h1>Find your sport.<br /><em>Find your people.</em></h1><p>One place to discover athletes, connect with the right players, find events and build your sports community.</p><div className="hero-actions"><Link href="/onboarding" className="button-lime">Get started <ArrowRight size={17} /></Link><a href="#sports" className="button-hero-quiet"><Play size={15} fill="currentColor" /> Explore sports</a></div><div className="hero-proof"><div className="avatar-stack">{athletes.slice(0, 4).map((athlete) => <img src={athlete.avatar} alt="" key={athlete.id} />)}</div><span>Already connecting players around Hyderabad.</span></div></motion.div></div><div className="hero-network" aria-hidden="true"><div className="network-line line-one" /><div className="network-line line-two" /><div className="network-node node-one"><span>⌁</span><small>Badminton</small></div><div className="network-node node-two"><span>◒</span><small>Cricket</small></div><div className="network-node node-three"><span>↗</span><small>Running</small></div><div className="network-node node-four"><span>♞</span><small>Chess</small></div></div></section>
      <section className="fragment-section"><div><SectionKicker>THE PROBLEM</SectionKicker><h2>Sports shouldn’t be<br />this fragmented.</h2><p>The best people to play with are often already nearby—just scattered between chat groups, closed apps and random contacts.</p></div><div className="fragment-visual"><div className="fragment-row broken"><span>WhatsApp group</span><i>→</i><span>Separate apps</span><i>→</i><span>Missed sessions</span></div><div className="fragment-row connected"><span className="mini-mark">C</span><div><b>One place. One athlete identity.</b><small>Discover • Connect • Play • Repeat</small></div><CheckCircle2 size={22} /></div></div></section>
      <section className="numbers-section"><div><p>DEMO PLATFORM NUMBERS</p><strong><Counter value={12} suffix="+" /></strong><span>Sports supported</span></div><div><p>LOCAL COMMUNITY</p><strong><Counter value={1200} suffix="+" /></strong><span>Athlete identities</span></div><div><p>PLAYERS CONNECTED</p><strong><Counter value={300} suffix="+" /></strong><span>Connections made</span></div><div><p>ON THE CALENDAR</p><strong><Counter value={80} suffix="+" /></strong><span>Upcoming events</span></div></section>
      <section className="how-section" id="how-it-works"><div className="section-intro"><SectionKicker>THE SIMPLE ROUTE</SectionKicker><h2>From “who’s free?”<br />to <em>“see you on court.”</em></h2></div><div className="how-timeline">{[["01", "Build your sports identity", "Create your profile and choose the sports you actually play.", UserIcon], ["02", "Discover", "Find compatible athletes and events around your schedule.", Compass], ["03", "Connect", "Send a request, make friends and start a sport-focused chat.", UsersRound], ["04", "Play", "Lock the session, show up and grow your trusted circle.", ShieldCheck]].map(([number, title, copy, Icon]) => { const I = Icon as typeof Compass; return <article key={number as string}><span>{number as string}</span><i /><I size={21} /><h3>{title as string}</h3><p>{copy as string}</p></article>; })}</div></section>
      <section className="sports-section" id="sports"><div className="sports-feature-copy"><SectionKicker>MEET THE RIGHT PERSON</SectionKicker><h2>Compatibility that<br />you can <em>actually read.</em></h2><p>Every recommendation has a reason: the sport, the rhythm, the distance, and the availability that make a good game more likely.</p><div className="reason-list"><span><CheckCircle2 size={18} />Comparable skill</span><span><CheckCircle2 size={18} />Nearby and available</span><span><CheckCircle2 size={18} />Shared sporting intent</span></div><Link href="/onboarding" className="text-link">See how matching works <ArrowRight size={16} /></Link></div><div className="sports-feature-card"><div className="recommendation-label"><span>Recommended for you</span><b>94% Match</b></div><AthleteCard athlete={athletes[0]} onConnect={() => {}} onView={() => {}} onMatch={() => {}} /></div></section>
      <section className="pricing-section"><div className="section-intro"><SectionKicker>CHOOSE YOUR RITUAL</SectionKicker><h2>Start playing now.<br /><em>Upgrade when it earns it.</em></h2><p>All prices are demo pricing. Payments are not enabled in this prototype.</p></div><div className="pricing-grid">{subscriptionPlans.map((plan) => <PricingCard key={plan.name} plan={plan} onSelect={() => { window.location.href = "/onboarding"; }} />)}</div></section>
      <section className="locations-section"><div><SectionKicker>BUILT FOR LOCAL PLAY</SectionKicker><h2>Your club can travel<br />with you.</h2><Link href="/onboarding" className="text-link">Explore athletes in another city <ArrowRight size={16} /></Link></div><div className="city-grid">{cities.map((city, index) => <button key={city} className={index === 0 ? "active" : ""}><MapPin size={16} />{city}<ChevronRight size={15} /></button>)}</div></section>
      <section className="faq-section" id="faq"><div className="faq-copy"><SectionKicker>GOOD QUESTIONS</SectionKicker><h2>The fine print,<br />without the <em>fence-sitting.</em></h2><p>ClubOfSports is designed to make local sport feel easy to organize and safe to return to.</p></div><Accordion type="single" collapsible className="faq-list">{faqs.map(([question, answer], index) => <AccordionItem value={`faq-${index}`} key={question}><AccordionTrigger>{question}</AccordionTrigger><AccordionContent>{answer}</AccordionContent></AccordionItem>)}</Accordion></section>
      <section className="final-cta"><div><BrandMark /><h2>Your next game starts<br />with one good connection.</h2></div><Link href="/onboarding" className="button-lime">Build your identity <ArrowRight size={17} /></Link></section>
    </main><footer className="landing-footer"><BrandMark compact /><p>© 2026 ClubOfSports. A connected place to play.</p><div><a href="#faq">FAQ</a><a href="#sports">Sports</a><a href="#how-it-works">How it works</a></div></footer>
  </div>;
}

function UserIcon(props: { size?: number }) { return <span className="how-user-icon" {...props}>◌</span>; }
